pipeline {
    agent {label: 'slave1'}
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    pwd
                    dir
                    echo "I am in build step"
                    ./gradlew build -x test
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }

        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                    docker build -t my-web-server -f ./.infra/docker/Dockerfile .
                    docker commit my-web-server:latest
                    pwd
                    dir
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage"
                    docker tag my-web-server:latest chaturvedirishabh91/my-web-server:latest
                    docker push chaturvedirishabh91/my-web-server:latest
                ''',
            label: "Publishing Docker Image"
            }
        }
    }

    post{
    	always{
		deleteDir()
	}
    }
}

